### ISSUE TITLE
Support `notation` field for spaces/properties?

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/web#159]
Decided not to veer https://github.com/pi-base/data/pull/657 off-topic.

Once upon a time I pushed for non-mathematical names for our spaces. Now I'm wondering if I had it backwards: as the pi-base goes deeper into the weeds, we're going to wind up with more examples that don't have names besides maybe "Example x.y.z". But usually there's some kind of notation that could be used to describe these. So maybe...

```yaml
uid: S000101
notation: \omega^{\mathfrak c}
name: Continuum power of a countable discrete space
aliases:
  - Uncountable products of $Z^+$
keywords:
  - (any words that someone might reasonably use to find this space but didn't fit into notation/name/aliases)
counterexamples_id: 103 # (unused, probably should be deprecated anyway)
refs:
- doi: 10.1007/978-1-4612-6290-9
  name: Counterexamples in Topology
```

And then we start displaying something like

> $\omega^{\mathfrak c}$ (Continuum power of a countable discrete space)

And maybe only one of notation or name is required, displaying

> $\omega^{\mathfrak c}$

or

> Continuum power of a countable discrete space

if the other is missing.

I'm also curious what @awswan and @lunar-starlight think over at the topos fork.
